[project]
name = ""
version = ""
description = ""
authors = [
    {name = "JiangXiaoqiang", email = "jiangtingqiang@gmail.com"},
]
dependencies = [
    "diagrams>=0.23.4",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

